---
- name: Terminante instance.
  ec2:
    instance_ids: "{{ varinstance }}"
    wait: true
    state: absent
    region: us-east-1
    aws_access_key: "{{ varawskey }}"
    aws_secret_key: "{{ varawssecret }}"
