---
- name: Terminate instance
  ec2:
   instance_ids: "{{ var_instance }}"
   wait: true
   state: absent
   region: us-east-1
   aws_access_key: "{{ var_aws_key }}"
   aws_secret_key: "{{ var_aws_secret }}""

  register: ec2
- name: Print all ec2 variables
  debug: var=ec2
