---
- name: Terminate instance
  ec2:
    instance_ids: "{{ varinstance }}"
    wait: true
    state: absent
    region: us-east-1
    aws_access_key: "{{ varawskey }}"
    aws_secret_key: "{{ varawssecret }}"

register: ec2
- name: Print all ec2 variables
  debug: var=ec2
